DROP DATABASE IF EXISTS DB_TCCGRUPO6;
CREATE DATABASE DB_TCCGRUPO6;

USE DB_TCCGRUPO6;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, EMAIL VARCHAR(100) NOT NULL
	, SENHA VARCHAR(45) NOT NULL
);

CREATE TABLE EQUIPE (
        IDEQUIPE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
        , NOME VARCHAR (100) NOT NULL
);

CREATE TABLE ESTRATEGIA (
        IDESTRATEGIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
        , NOME VARCHAR (100) NOT NULL
        , TIPO VARCHAR (100) NOT NULL
        , MAPA VARCHAR (100) NOT NULL

);

CREATE TABLE ACAO (
        IDACAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
        , NOME VARCHAR (100) NOT NULL
);

CREATE TABLE PAPEL(
        IDPAPEL INT NOT NULL PRIMARY KEY AUTO_INCREMENT
        , NOME VARCHAR (100) NOT NULL

);

CREATE TABLE DETALHE (
        IDDETALHE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
        , POSX VARCHAR (100) NOT NULL
        , POSY VARCHAR (100) NOT NULL
);

CREATE TABLE PARTICIPA (
        IDPARTICIPA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
        , DT_INGRESSO DATE NOT NULL
);