DROP DATABASE IF EXISTS DB_TCCGRUPO6;
CREATE DATABASE DB_TCCGRUPO6;

USE DB_TCCGRUPO6;

CREATE TABLE USUARIO (
	IDUSUARIO INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, NOME VARCHAR(100) NOT NULL
	, EMAIL VARCHAR(100) NOT NULL
	, SENHA VARCHAR(45) NOT NULL
);

CREATE TABLE EQUIPE (
    IDEQUIPE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
    